<nav id="main-navigation">
	<ul>
		<li><a href="#" title="">Home</a></li>
		<li><a href="#" title="">Browse/Find</a></li>
		<li><a href="#" title="">Events</a></li>
		<li><a href="#" title="">Contribute</a></li>
		<li><a href="about.php" title="About ADI">About</a></li>
	</ul>
</nav>
<nav id="secondairy-navigation">
	<ul>
		<li>Grid <span> </span>
		<div id="slider"></div> 
		</li>
		<li>Homepage Columns:
			<ul class="options-columns">
				<li><a href="#1" title="">1</a></li>
				<li><a href="#2" title="">2</a></li>
				<li><a href="#3" title="">3</a></li>
			</ul>
		</li>
		<li><a href="todo.php">To do</a></li>
	</ul>
</nav>